made basic user signup
ppauljonathan/quora-clone pull request #1
Opened 2023-05-10 13:32 UTC by ppauljonathan

Changes made:
  user signup page
  mailer to send verification code to user
  validating verification code

2023-05-18 06:12 UTC, shubhamjuneja1 requested changes

2023-05-18 07:44 UTC, ppauljonathan commented on db/schema.rb
> +    t.boolean "is_admin", default: false
added `enum role: %i[user admin], default: :user`

2023-05-18 07:46 UTC, ppauljonathan commented on config/routes.rb
> +  resources :users, id: /\d+/, except: %i[new create] do
i had done it to ensure that `:id` is always an integer, removed now

2023-05-18 07:50 UTC, ppauljonathan commented on config/routes.rb
> +      get 'email_verification'
redone this with devise-like controllers

2023-05-18 08:11 UTC, ppauljonathan commented on app/controllers/application_controller.rb
> +    return if session[:user_id]
done

2023-05-18 08:12 UTC, ppauljonathan commented on app/controllers/application_controller.rb
> +    @current_user = User.find(session[:user_id])
done

2023-05-18 10:10 UTC, ppauljonathan commented on app/controllers/confirmations_controller.rb
> +    return unless params[:token]
done

2023-05-18 10:36 UTC, ppauljonathan commented on app/controllers/confirmations_controller.rb
> +    if user.try :verify
done

2023-05-18 10:36 UTC, ppauljonathan commented on app/controllers/confirmations_controller.rb
> +    if user.try :resend_verification_mail
done

2023-05-18 10:37 UTC, ppauljonathan commented on lib/tasks/admin/new.rake
> +      user.is_admin = true
done

2023-05-18 10:38 UTC, ppauljonathan commented on app/models/user.rb
> +  validates :email, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
done

2023-05-18 10:56 UTC, ppauljonathan commented on app/controllers/sessions_controller.rb
> +    session[:user_id] = nil
done

2023-05-18 10:56 UTC, ppauljonathan commented on app/controllers/sessions_controller.rb
> +    session[:user_id] = @user.id
done

2023-05-18 11:01 UTC, ppauljonathan commented on app/controllers/sessions_controller.rb
> +    cookies.signed[:user_id] = { value: @user.id, expires: 24.weeks.from_now } if user_params[:remember_me]
done

2023-05-18 11:02 UTC, ppauljonathan commented on app/controllers/application_controller.rb
> +    @current_user ||= User.find_by_id(session[:user_id] || cookies.signed[:user_id])
done

2023-05-18 11:14 UTC, ppauljonathan commented on app/controllers/passwords_controller.rb
> +    return if @user
changed to before_action

2023-05-18 11:52 UTC, ppauljonathan commented on app/mailers/user_mailer.rb
> +    @user = User.find(user_id)
mad before_action

2023-05-18 12:10 UTC, ppauljonathan commented on app/controllers/passwords_controller.rb
> +    if @user.update(password: user_params[:password])
i have made a check box for show password so we may not need confirmation_password

2023-05-18 12:57 UTC, ppauljonathan commented on lib/tasks/admin/new.rake
> +      user.credits = 5
done

2023-05-18 12:57 UTC, ppauljonathan commented on app/models/user.rb
> +    send_verification_email
done

2023-05-18 13:00 UTC, ppauljonathan commented on app/models/user.rb
> +    return false unless update(verification_token: generate_token(:verification), verified_at: nil)
done

2023-05-18 13:00 UTC, ppauljonathan commented on app/controllers/users_controller.rb
> +    params.require(:user).permit(:name, :profile_picture)
done in next PR

2023-05-22 21:05 UTC, shubhamjuneja1 commented on app/controllers/sessions_controller.rb
> +    return if @user.try(:authenticate, user_params[:password])
do we need to use try here?

2023-05-22 21:12 UTC, shubhamjuneja1 approved these changes

2023-05-23 04:53 UTC, ppauljonathan commented on app/controllers/sessions_controller.rb
> +    return if @user.try(:authenticate, user_params[:password])
no need, removed from here

2023-05-23 04:55 UTC, merged