made admin panel for users and questions
ppauljonathan/quora-clone pull request #11
Opened 2023-06-06 14:36 UTC by ppauljonathan

made admin panel for user and questions unpublishing

2023-06-11 21:54 UTC, shubhamjuneja1 requested changes

2023-06-11 21:54 UTC, shubhamjuneja1 commented on app/models/user.rb
> +  def soft_destroy
rename to mark_disabled

2023-06-11 21:54 UTC, shubhamjuneja1 commented on app/models/question.rb
> +    update(published_at: nil, save_as_draft: true)
what is save_as_draft doing here?

2023-06-11 21:54 UTC, shubhamjuneja1 commented on app/controllers/admin/users_controller.rb
> +  before_action :check_admin
all admin controllers should inherit from base_controller in admin which should have this before_action

2023-06-12 13:45 UTC, ppauljonathan commented on app/models/question.rb
> +    update(published_at: nil, save_as_draft: true)
moved to concern, changed to `update_columns`, so as to not trigger callbacks

2023-06-13 04:55 UTC, ppauljonathan commented on app/controllers/admin/users_controller.rb
> +  before_action :check_admin
done

2023-06-28 18:15 UTC, shubhamjuneja1 requested changes
Changes

2023-06-28 18:15 UTC, shubhamjuneja1 approved these changes

2023-06-30 10:03 UTC, merged