Feature/answers
ppauljonathan/quora-clone pull request #3
Opened 2023-05-22 10:54 UTC by ppauljonathan

Made users able answer questions and displayed answers on the same page and also made CRUD of answers

2023-05-25 08:02 UTC, shubhamjuneja1 requested changes

2023-05-25 10:13 UTC, ppauljonathan commented on app/controllers/users_controller.rb
> +    @answers = @answers.published unless @user == current_user
removed

2023-05-25 10:14 UTC, ppauljonathan commented on app/controllers/users_controller.rb
> +    render :show
removed

2023-05-25 10:14 UTC, ppauljonathan commented on app/models/user.rb
> +  scope :with_topics, -> { includes :topics }
removed

2023-06-11 19:45 UTC, shubhamjuneja1 requested changes

2023-06-11 19:45 UTC, shubhamjuneja1 commented on app/views/questions/show.html.erb
> +<% if @question.published_at? %>
why do we need this check?
users will only this when question is published
question's owner can see this, no harm

2023-06-11 19:45 UTC, shubhamjuneja1 commented on app/views/questions/_question_file_attachments.html.erb
> +    <% @question.files_attachments.each do |file| %>
have you eager loaded files_attachments?

2023-06-11 19:45 UTC, shubhamjuneja1 commented on app/controllers/questions_controller.rb
> +                              .per(QUESTIONS_PER_PAGE)
have you checked kaminari?
there is a default for this, which you can override in models

2023-06-12 06:39 UTC, ppauljonathan commented on app/views/questions/show.html.erb
> +<% if @question.published_at? %>
removed form here

2023-06-12 06:40 UTC, ppauljonathan commented on app/views/questions/_question_file_attachments.html.erb
> +    <% @question.files_attachments.each do |file| %>
```ruby
private def set_question
    @question = Question.includes(:topics,
                                  :files_attachments,
                                  :rich_text_content,
                                  { user: :profile_picture_attachment },
                                  { answers: :rich_text_content })
                        .find_by_url_slug(params[:url_slug])
  end
```
yes

2023-06-12 06:44 UTC, ppauljonathan commented on app/controllers/questions_controller.rb
> +                              .per(QUESTIONS_PER_PAGE)
resolved in next PR #5
[here](https://github.com/ppauljonathan/quora-clone/blob/1ba328c46dd6dd8638178a564f290576e4de797c/app/controllers/questions_controller.rb#L34l)

2023-06-13 21:35 UTC, shubhamjuneja1 approved these changes

2023-06-14 04:41 UTC, merged