Feature/comments
ppauljonathan/quora-clone pull request #5
Opened 2023-05-26 15:14 UTC by ppauljonathan

added basic CRUD to comments

2023-05-30 11:05 UTC, shubhamjuneja1 requested changes

2023-05-30 11:58 UTC, ppauljonathan commented on app/controllers/application_controller.rb
> +    cookies.delete :user_id unless @set_current_user
had done this because there was an error if a cookie has been made of a non existent user, so have made it so that the cookie is deleted

2023-05-31 06:04 UTC, ppauljonathan commented on app/controllers/answers_controller.rb
> +                       .per(COMMENTS_PER_PAGE)
done

2023-05-31 06:05 UTC, ppauljonathan commented on app/controllers/application_controller.rb
> +  private def set_current_user
renamed back to `current_user`

2023-05-31 09:43 UTC, ppauljonathan commented on app/controllers/application_controller.rb
> +    cookies.delete :user_id unless @set_current_user
made this as `helper_method`

2023-06-11 20:09 UTC, shubhamjuneja1 requested changes

2023-06-11 20:09 UTC, shubhamjuneja1 commented on app/views/comments/_comment.html.erb
> +    <% if comment.commentable.class == Question %>
if we add another class, you will need to handle here
can we create some generic helper method here?

2023-06-12 07:34 UTC, ppauljonathan commented on app/views/comments/_comment.html.erb
> +    <% if comment.commentable.class == Question %>
moved logic to a helper method

2023-06-13 20:50 UTC, shubhamjuneja1 approved these changes

2023-06-14 04:42 UTC, merged