added report abuse feature
ppauljonathan/quora-clone pull request #6
Opened 2023-05-27 13:22 UTC by ppauljonathan

added report abuse feature

2023-05-30 11:08 UTC, shubhamjuneja1 commented on db/migrate/20230527125437_add_reported_at_to_resource.rb
> +      add_column table, :reported_at, :timestamp
why do you need this?
For any new entity, you will need to ad this again
If we are already making it polymorphic, we can directly fetch from there

2023-05-30 11:10 UTC, shubhamjuneja1 commented on app/javascript/report_abuse.js
> +reportAbuse = (reportableType, reportableId) => {
ok for now but try to spend much time from js from next time, use html request unless told

2023-05-30 11:31 UTC, shubhamjuneja1 commented on app/models/comment.rb
> +  default_scope { order(created_at: :desc).where(reported_at: nil) }
just mark those unpublish instead of this

2023-05-31 07:20 UTC, ppauljonathan commented on db/migrate/20230527125437_add_reported_at_to_resource.rb
> +      add_column table, :reported_at, :timestamp
removed

2023-05-31 07:27 UTC, ppauljonathan commented on app/models/comment.rb
> +  has_many :reports, as: :reportable
done

2023-05-31 07:27 UTC, ppauljonathan commented on app/models/comment.rb
> +  default_scope { order(created_at: :desc).where(reported_at: nil) }
done

2023-06-11 20:34 UTC, shubhamjuneja1 requested changes

2023-06-11 20:34 UTC, shubhamjuneja1 commented on app/views/answers/_answer.html.erb
> +<%= link_to 'Edit', edit_answer_path(answer.id), class: 'edit-question-button' if current_user == answer.user %>
current_user == answer.user
this could be generic like

abc(resource)
resource.user == current_user

2023-06-11 20:34 UTC, shubhamjuneja1 commented on app/models/report.rb
> +class Report < ApplicationRecord
it's not a good name, it can be AbuseReport

2023-06-11 20:34 UTC, shubhamjuneja1 commented on app/models/report.rb
> +    reportable.update(published_at: nil)
call unpublish method which should be in a concern

2023-06-11 20:34 UTC, shubhamjuneja1 commented on app/models/comment.rb
> +  has_many :reports, as: :reportable
already in AbuseReportable

2023-06-11 20:34 UTC, shubhamjuneja1 commented on app/models/answer.rb
> +  default_scope { order(created_at: :desc).where.not(published_at: nil) }
this scope could be in common

2023-06-12 08:16 UTC, ppauljonathan commented on app/models/comment.rb
> +  has_many :reports, as: :reportable
removed

2023-06-12 08:20 UTC, ppauljonathan commented on app/models/report.rb
> +class Report < ApplicationRecord
done

2023-06-12 08:22 UTC, ppauljonathan commented on app/models/report.rb
> +    reportable.update(published_at: nil)
done

2023-06-12 08:27 UTC, ppauljonathan commented on app/models/answer.rb
> +  default_scope { order(created_at: :desc).where.not(published_at: nil) }
moved to concern

2023-06-13 20:52 UTC, shubhamjuneja1 commented on app/models/concerns/abuse_reportable.rb
> +  private def publish
this doesn't make sense in this concern

2023-06-13 20:53 UTC, shubhamjuneja1 approved these changes

2023-06-14 04:46 UTC, merged