Feature/upvotes
ppauljonathan/quora-clone pull request #8
Opened 2023-05-31 05:29 UTC by ppauljonathan

made users able to upvote and downvote comments and answers using FETCH API request

2023-06-11 21:45 UTC, shubhamjuneja1 requested changes

2023-06-11 21:45 UTC, shubhamjuneja1 commented on config/routes.rb
> +  controller :votes do
scope controller: :votes, path: 'vote' do
    post 'upvote'
    post 'downvote'
  end

2023-06-11 21:45 UTC, shubhamjuneja1 commented on app/models/vote.rb
> +    unvote: 0
why this?
if user is unvoting, vote should be deleted

2023-06-11 21:45 UTC, shubhamjuneja1 commented on app/models/vote.rb
> +  enum :vote_type, VOTE_TYPES, default: :unvote
no default needed

2023-06-11 21:45 UTC, shubhamjuneja1 commented on app/models/question.rb
> +    debugger
remove

2023-06-11 21:45 UTC, shubhamjuneja1 commented on app/models/concerns/votable.rb
> +    vote.nil? ? :unvote : vote.vote_type
should be deleted

2023-06-11 21:45 UTC, shubhamjuneja1 commented on app/controllers/votes_controller.rb
> +    @vote.vote_type = @vote.downvote? ? :unvote : :downvote
remove unvote here as well

2023-06-11 21:45 UTC, shubhamjuneja1 commented on app/controllers/votes_controller.rb
> +        @vote.votable.set_net_upvotes
should be automatic, not in controller

2023-06-11 21:45 UTC, shubhamjuneja1 commented on app/models/answer.rb
> +  private def set_credits
should be in voteable concern

2023-06-11 21:45 UTC, shubhamjuneja1 commented on app/models/answer.rb
> +      user.increment!(:credits, 1)
you should call
user.update_credits
and in that you should create entry for 
credit_transactions.build()

2023-06-11 21:45 UTC, shubhamjuneja1 commented on app/controllers/comments_controller.rb
> +    @comment.published_at = Time.now
not needed

2023-06-11 21:45 UTC, shubhamjuneja1 commented on app/controllers/comments_controller.rb
> +    @comment.published_at = Time.now
or in model atleast

2023-06-11 21:45 UTC, shubhamjuneja1 commented on app/controllers/answers_controller.rb
> +    @answer.published_at = Time.now
same as comment

2023-06-12 09:55 UTC, ppauljonathan commented on app/controllers/answers_controller.rb
> +    @answer.published_at = Time.now
done

2023-06-12 09:57 UTC, ppauljonathan commented on app/models/question.rb
> +    debugger
done

2023-06-12 09:59 UTC, ppauljonathan commented on app/controllers/comments_controller.rb
> +    @comment.published_at = Time.now
removed

2023-06-12 10:02 UTC, ppauljonathan commented on app/models/vote.rb
> +    unvote: 0
removed

2023-06-12 10:02 UTC, ppauljonathan commented on app/models/vote.rb
> +  enum :vote_type, VOTE_TYPES, default: :unvote
removed

2023-06-12 10:04 UTC, ppauljonathan commented on app/models/concerns/votable.rb
> +    vote.nil? ? :unvote : vote.vote_type
done

2023-06-12 11:38 UTC, ppauljonathan commented on app/controllers/votes_controller.rb
> +    @vote.vote_type = @vote.downvote? ? :unvote : :downvote
done

2023-06-12 11:44 UTC, ppauljonathan commented on app/controllers/votes_controller.rb
> +        @vote.votable.set_net_upvotes
done

2023-06-12 11:55 UTC, ppauljonathan commented on app/models/answer.rb
> +  private def set_credits
done

2023-06-12 12:00 UTC, ppauljonathan commented on app/models/answer.rb
> +      user.increment!(:credits, 1)
done
will do
> and in that you should create entry for
credit_transactions.build()

in the next PR as there i have made `credit_transactions`

2023-06-14 07:48 UTC, ppauljonathan commented on app/models/answer.rb
> +      user.increment!(:credits, 1)
leaving for now as discussed

2023-06-16 04:49 UTC, ppauljonathan commented on app/models/answer.rb
> +      user.increment!(:credits, 1)
added `credit_logs` model as i have used `credit_transactions` to store stripe transaction details

2023-06-28 08:24 UTC, shubhamjuneja1 commented on app/controllers/votes_controller.rb
> +      render json: { vote_type: @vote.vote_type,
we can use serializer here

2023-06-28 08:38 UTC, shubhamjuneja1 commented on app/controllers/votes_controller.rb
> +    if @vote.vote :up
@voteable.upvote

2023-06-28 08:50 UTC, shubhamjuneja1 commented on app/models/concerns/votable.rb
> +    update(net_upvote_count: upvotes - downvotes)
Is this net_upvote_count or net_votes?
What if someone has only downvoted, this will be -1

2023-06-28 08:52 UTC, shubhamjuneja1 commented on app/models/user.rb
> +    increment!(:credits, amount)
this should be in callback of credit_log create

2023-06-28 08:53 UTC, shubhamjuneja1 commented on config/routes.rb
> +  get 'credit_logs' => 'credit_logs#index'
resource, only index?

2023-06-28 09:31 UTC, ppauljonathan commented on config/routes.rb
> +  get 'credit_logs' => 'credit_logs#index'
done

2023-06-28 09:36 UTC, ppauljonathan commented on app/models/user.rb
> +    increment!(:credits, amount)
done

2023-06-28 12:08 UTC, ppauljonathan commented on app/controllers/votes_controller.rb
> +    if @vote.vote :up
done this as there is a common method `vote`

```ruby
  def vote(type, user_id)
    vote = votes.find_or_create_by(user_id: user_id)
    return vote.destroy if vote.public_send("#{type}vote?")

    vote.public_send "#{type}vote!"
  end
```

in the votable concern

2023-06-28 12:08 UTC, ppauljonathan commented on app/controllers/votes_controller.rb
> +                     destroyed: @vote.destroyed? },
removed

2023-06-28 12:09 UTC, ppauljonathan commented on app/controllers/votes_controller.rb
> +      render json: { vote_type: @vote.vote_type,
done

2023-06-28 12:09 UTC, ppauljonathan commented on app/models/concerns/votable.rb
> +    update(net_upvote_count: upvotes - downvotes)
`net_upvote_count` has been specified in the document

2023-06-28 13:33 UTC, shubhamjuneja1 commented on app/models/concerns/votable.rb
> +    before_update :set_credits, :remove_credits_if_unpublished
why before_update?
It's not like, we are validation or something, it can be in after_callback

2023-06-28 14:57 UTC, shubhamjuneja1 requested changes

2023-06-28 14:57 UTC, shubhamjuneja1 commented on app/models/concerns/votable.rb
> +    downvotes = votes.downvote.count
use one query to fetch count and use ruby to calculate total in optimized way

2023-06-28 14:57 UTC, shubhamjuneja1 commented on app/controllers/votes_controller.rb
> +    if @voteable.vote :down, current_user.id
I think, I asked you to 
@voteable.downvote

2023-06-28 14:57 UTC, shubhamjuneja1 commented on app/models/concerns/votable.rb
> +    return unless changes[:published_at]
why do we need this?

2023-06-28 14:57 UTC, shubhamjuneja1 commented on app/models/concerns/votable.rb
> +    if net_upvote_count >= MIN_NET_UPVOTES_FOR_CREDIT && net_upvote_count_was <= MIN_NET_UPVOTES_FOR_CREDIT
Can't we just use
net_upvote_count == MIN_NET_UPVOTES_FOR_CREDIT
update

2023-06-29 09:04 UTC, ppauljonathan commented on app/models/concerns/votable.rb
> +    before_update :set_credits, :remove_credits_if_unpublished
added to after_commit also moved `remove_credits_if_unpublished` to `AbuseReportable` as it is unpublished only when abuse reported

2023-06-29 09:04 UTC, ppauljonathan commented on app/models/concerns/votable.rb
> +    return unless changes[:published_at]
removed from here and placed in `:if` option for the callback

2023-06-29 09:06 UTC, ppauljonathan commented on app/controllers/votes_controller.rb
> +    if @voteable.vote :down, current_user.id
done

2023-06-29 09:17 UTC, ppauljonathan commented on app/models/concerns/votable.rb
> +    downvotes = votes.downvote.count
done

2023-06-29 19:35 UTC, shubhamjuneja1 commented on app/models/concerns/votable.rb
> +    update(net_upvote_count: upvotes - downvotes)
vote_counts['upvote'].to_i - vote_counts['downvote'].to_i
but merging now

2023-06-29 19:35 UTC, shubhamjuneja1 approved these changes

2023-06-30 09:58 UTC, merged